#========================================
# Test profile settings (junit tests)
#========================================
logging:
  level:
    root: INFO
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.jdbc.autoconfigure.health.DataSourceHealthContributorAutoConfiguration
config:
  esigningprocess:
    base-url: http://localhost:59999/pw-esigning
    token-url: http://localhost:59999/token
    client-id: someClientId
    client-secret: someClientSecret
    connect-timeout: 5
    read-timeout: 30
  document:
    base-url: http://localhost:59999/document
    token-url: http://localhost:59999/token
    client-id: someClientId
    client-secret: someClientSecret
    connect-timeout: 5
    read-timeout: 30